// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3iyVVE5uYVOWbzCFOhJiLXQtOsZzUR1c',
    appId: '1:465272155163:web:c1dd84339bede111ea1cbe',
    messagingSenderId: '465272155163',
    projectId: 'meau-app-e5a56',
    authDomain: 'meau-app-e5a56.firebaseapp.com',
    storageBucket: 'meau-app-e5a56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-SBGEaBqJ0XLwhNw5lx9nSLSG6g1030',
    appId: '1:465272155163:android:92d8f252e75722baea1cbe',
    messagingSenderId: '465272155163',
    projectId: 'meau-app-e5a56',
    storageBucket: 'meau-app-e5a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJN1rM3qS0azhQ6sGwn4v6vBA8ZaHj060',
    appId: '1:465272155163:ios:0caf34ebb4c0250dea1cbe',
    messagingSenderId: '465272155163',
    projectId: 'meau-app-e5a56',
    storageBucket: 'meau-app-e5a56.appspot.com',
    iosClientId: '465272155163-elhigld88mqj6df0fta896le7a2o78jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.meauApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJN1rM3qS0azhQ6sGwn4v6vBA8ZaHj060',
    appId: '1:465272155163:ios:0caf34ebb4c0250dea1cbe',
    messagingSenderId: '465272155163',
    projectId: 'meau-app-e5a56',
    storageBucket: 'meau-app-e5a56.appspot.com',
    iosClientId: '465272155163-elhigld88mqj6df0fta896le7a2o78jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.meauApp',
  );
}
